#define SEG_TEST

#ifdef SEG_TEST

#define GTEST_LANG_CXX11 1 // Must be defined, otherwise Gtest complains

#define BIG_HEADER
#define CHUNKED_ALLOCATOR_TEST
//#define SEG_POD_TEST
#define EXTERNAL_TEST
#define INTERNAL_TEST

#ifdef EXTERNAL_TEST

#define EXTERNAL_COMPLETE_TEST

#endif // EXTERNAL_TEST


#ifdef INTERNAL_TEST 

#define INTERNAL_FLAT_INSERT_TEST
#define INTERNAL_FLAT_ERASE_TEST
#define INTERNAL_SEGMENT_SLIDE_TEST
#define INTERNAL_SEGMENT_MOVE_TEST
#define INTERNAL_INDEX_TEST
#define INTERNAL_SEGMENTED_INSERT_TEST
#define INTERNAL_SEGMENTED_ERASE_TEST
#define INTERNAL_SEARCH_TEST

#endif // INTERNAL_TEST

#endif // SEG_TEST